export const ROUTES = {
  HOME: "/",
  PRICING: "/pricing",
  ABOUT: "/about",
  USE_CASES: "/use-cases",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  OVERVIEW: "/overview",
  CUSTOMERS: "/customers",
  PIPELINE: "/pipeline",
  COPILOT: "/copilot",
  REPORTS: "/reports",
  PLAYBOOKS: "/playbooks",
  INTEGRATIONS: "/integrations",
  SETTINGS: "/settings",
  SETTINGS_TEAM: "/settings/team",
  SETTINGS_BILLING: "/settings/billing",
  COMPLIANCE: "/compliance",
  COMPLIANCE_AUDIT: "/compliance/audit",
  COMPLIANCE_REPORTS: "/compliance/reports",
} as const;
